apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: recommendation-destination
  namespace: recommendation
spec:
  host: recommendationservice.recommendation.svc.cluster.local
  subsets:
  - labels:
      version: v1
    name: v1