apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendation
spec:
  hosts:
  - recommendationservice.recommendation.svc.cluster.local
  http:
  - fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 20s
    route:
    - destination:
        host: recommendationservice.recommendation.svc.cluster.local
        subset: v1