# Stateless application specification
# The Deployment creates a single replicated Pod, indicated by the 'replicas' field
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eap-app-prod
    migrate-for-anthos-optimization: "true"
    migrate-for-anthos-version: v1.11.1
  name: eap-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eap-app-prod
      migrate-for-anthos-optimization: "true"
      migrate-for-anthos-version: v1.11.1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eap-app-prod
        migrate-for-anthos-optimization: "true"
        migrate-for-anthos-version: v1.11.1
    spec:
      containers:
      - env:
        - name: HC_V2K_SERVICE_MANAGER
          value: "true"
        image: gcr.io/poc-migrate-for-anthos/eap-app:6-8-2022--14-19-0
        imagePullPolicy: IfNotPresent
        name: eap-app-prod
        resources: {}
      imagePullSecrets:
      - name: gcr-json-key  

---
# Service specification -
# This specification creates a new Service object which targets TCP port 8080 on any Pod with the "app"="eap-app-prod" label
# You can expose this service using a native LoadBalancer by adding "type: LoadBalancer" to the spec
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    migrate-for-anthos-optimization: "true"
    migrate-for-anthos-version: v1.11.1
  name: app-eap
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: eap-app-prod

---
# Service specification -
# This specification creates a new Service object which targets TCP port 9990 on any Pod with the "app"="eap-app-prod" label
# You can expose this service using a native LoadBalancer by adding "type: LoadBalancer" to the spec
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    migrate-for-anthos-optimization: "true"
    migrate-for-anthos-version: v1.11.1
  name: console-eap
spec:
  ports:
  - port: 9990
    protocol: TCP
    targetPort: 9990
  selector:
    app: eap-app-prod

---
