apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sblockloadbalancer
metadata:
  name: service-no-loadbalacer
  annotations:
    configmanagement.gke.io/cluster-selector: selector-type-anthos 
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
